controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
auth_check:
    path: /auth/check/{service}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
